[package]
name = "tuesday"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.82"
bincode = "1.3.3"
clap = { version = "4.5.4", features = ["derive"] }
colored = "2.1.0"
home = "0.5.9"
rustyline = "14.0.0"
serde = { version = "1.0.197", features = ["derive"] }
thiserror = "1.0.58"
